//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Context : DbContext
    {
        public Context()
            : base("name=Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Болезни> Болезни { get; set; }
        public virtual DbSet<Врачи> Врачи { get; set; }
        public virtual DbSet<Запись_на_приемы> Запись_на_приемы { get; set; }
        public virtual DbSet<Медицинские_карты> Медицинские_карты { get; set; }
        public virtual DbSet<Пациенты> Пациенты { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Расписание_врачей> Расписание_врачей { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<Стоимость_услуг> Стоимость_услуг { get; set; }
        public virtual DbSet<Услуги> Услуги { get; set; }
    }
}
