//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalRecords
    {
        public int MedicalRecordID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> DiseaseID { get; set; }
        public int CardNumber { get; set; }
        public string BloodType { get; set; }
    
        public virtual Diseases Diseases { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
