//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recording_a_procedure
    {
        public int Recording_a_procedureID { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public Nullable<int> ProcedureID { get; set; }
        public System.DateTime Date_and_time { get; set; }
        public string C_Description { get; set; }
    
        public virtual C_Procedures C_Procedures { get; set; }
        public virtual Appointments Appointments { get; set; }
    }
}
