//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesCost
    {
        public int ServiceCostID { get; set; }
        public Nullable<int> ProcedureID { get; set; }
        public decimal Cost { get; set; }
        public string Discount { get; set; }
    
        public virtual C_Procedures C_Procedures { get; set; }
    }
}
