//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Запись_на_приемы
    {
        public int ID_записи_на_прием { get; set; }
        public Nullable<int> ID_врача { get; set; }
        public System.DateTime Дата_и_время { get; set; }
        public string Описание { get; set; }
        public Nullable<int> ID_услуги { get; set; }
        public Nullable<int> ID_пациента { get; set; }
    
        public virtual Врачи Врачи { get; set; }
        public virtual Пациенты Пациенты { get; set; }
        public virtual Услуги Услуги { get; set; }
    }
}
