//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Медицинские_карты
    {
        public int ID_медицинской_карты { get; set; }
        public Nullable<int> ID_пациента { get; set; }
        public string Номер_карты { get; set; }
        public string Группа_крови { get; set; }
        public string Результат_болезни { get; set; }
    
        public virtual Пациенты Пациенты { get; set; }
    }
}
