//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расписание_врачей
    {
        public int ID_расписание { get; set; }
        public Nullable<int> ID_врача { get; set; }
        public string День_недели { get; set; }
        public System.TimeSpan Время_начало { get; set; }
        public System.TimeSpan Время_окончания { get; set; }
    
        public virtual Врачи Врачи { get; set; }
    }
}
